config/routes.rb
Rails.application.routes.draw do
  resources :public_recipes, only: [:index]
  devise_for :users
  root to: "users#show"
  get 'general_shopping_list', to: 'shopping_list#index'
  resources :users
  resources :foods
  
  resources :recipes do
    resources :recipe_foods    
  end

  resources :recipes
  resources :recipe_foods
  resources :shopping_list

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :user_id
  has_many :recipe_foods, class_name: 'RecipeFood', foreign_key: :recipe_id
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = current_user.recipes.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe if @recipe.user_id == current_user.id
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.public
      @recipe.update(public: false)
      flash[:notice] = 'You have update the recipe status to private'
    else
      @recipe.update(public: true)
      flash[:notice] = 'You have update the recipe status to public'
    end
    redirect_to recipes_path
  end

  # DELETE /recipes/1
  def destroy
    @recipe = Recipe.find(params[:id])
    if current_user
      @recipe.destroy
      redirect_to recipes_path, notice: 'Recipe was successfully deleted.'
    else
      render recipes_path, notice: "You can't delete somebody else's account"
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.text_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.text_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<section class='recipe-show' >

  <p class='recipe-name'> <%= @recipe.name %> </p>

  <div>
    <p>
      <strong>Preparation time:</strong>
      <%= @recipe.preparation_time %>
    </p>

    <p>
      <strong>public:</strong>
      <%= @recipe.public %>
    </p>
  
  </div>
 
  <p>
    <strong>Cooking time:</strong>
    <%= @recipe.cooking_time %>
  </p>

  <p>
    <strong>Description:</strong>

    <%= @recipe.description %>

    <%= recipe.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= recipe.user_id %>
  </p>

  
</section>

app/views/recipes/index.html.erb
<section class= 'recipe-section'>
  <h1>All recipes</h1>

  <p style="color: green"><%= notice %></p> 
  
    <% @recipes.each do |recipe| %>
      <div class='recipe-card'>
        <div> 
          <p class='recipe-name'><%= link_to recipe.name, recipe %> </p>
          <p class='remove'><%= link_to 'Remove', recipe, data: { turbo_method: :delete } %></p>
        </div>

        <div>    
          <p class='recipe-description'>
            <%= recipe.description %>    
          </p>
        </div>    
      </div>  
      
    <% end %>  

  <%= link_to "New recipe", new_recipe_path, class:'add-recipe' %>

</section>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<section>
  <% if @recipe.user_id == current_user.id  %>
    <div class='recipe-show' >

    <p style="color: green"><%= notice %> </p>

   <p class='recipe-name'> <%= @recipe.name %> </p>

    <div class='preparation-section'>
      <p>
        <strong>  Preparation time:</strong>
        <%= @recipe.preparation_time %>
      </p>

      <%=form_with url: recipe_path(@recipe), class: 'public-switch', method: "patch" do %>
              <label for="public-toggle" class="switch">
                <%= check_box_tag 'public' , @recipe.public, @recipe.public, id: "public-toggle" , onchange: "this.form.submit()" %>
                <span class="slider round"></span>
              </label>
      <% end %>
    
    </div>
  
    <div>
      <strong>Cooking time:</strong>
      <%= @recipe.cooking_time %>
    </div>
    
    <div>    
      <strong>Description:</strong>
      <%= @recipe.description %>  
    </div>

    <div>
      <strong>Steps go here...</strong>
    </div>

    <%= form_with(model:RecipeFood.new, url: recipe_recipe_foods_path(@recipe),class:'ingredient-section', method: :post) do |f| %>
      <div>
        <%= f.number_field :quantity, placeholder: 'Quantity', min: 0, step:0.01 %>
        <%= f.collection_select :food_id, @recipe.user.foods, :id, :name %>
      </div>
      <%= f.submit 'Add ingredient', class:'add-ingredient' %>
    <% end %>  


    <table>
      <thead>
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Value</th>
          <th>Actions</th>
          </tr>
      </thead>
      <tbody>
        <% @recipe.recipe_foods.each do |food_recipe| %>
        <tr>
          <td><%= food_recipe.food.name %></td>
          <td> <%= food_recipe.food.measurement_unit %> </td>
          <td>$ <%= food_recipe.food.price %></td>
          <td> 
          <div class='modify-delete'>
            <%= link_to "Modify" %> 
            <%= button_to "Remove" %>
          </div>       
          </td>
        </tr>
      <% end %>
    </tbody>
    </table>
    
    <%= link_to "Back to recipes", recipes_path %>
  </div>    
      
  <% else %>
    <h1> Oops! page restricted, You can't see others show page.</h1>    
  <% end %>
  
</section>