config/routes.rb
Rails.application.routes.draw do
  resources :public_recipes, only: [:index]
  devise_for :users
  root to: "users#show"
  get 'general_shopping_list', to: 'shopping_list#index'
  resources :users
  resources :foods
  
  resources :recipes do
    resources :recipe_foods    
  end

  resources :recipes
  resources :recipe_foods
  resources :shopping_list

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :user_id
  has_many :recipe_foods, class_name: 'RecipeFood', foreign_key: :food_id
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = current_user.foods.all
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = current_user.foods.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = current_user.foods.new(food_params)
    @food.user_id = current_user.id

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'New Food added successfully.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_path, notice: 'Food was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Measurement unit:</strong>
    <%= food.measurement_unit %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= food.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= food.quantity %>
  </p>

  <p>
    <strong>User:</strong>
    <%= food.user_id %>
  </p>

</div>

app/views/foods/_form.html.erb
<div class="food-form">
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="food-field">
    <%= form.text_field :name, class: 'food-field-input', placeholder: 'Name of the food' %>
  </div>

  <div class="food-field">
    <%= form.text_field :measurement_unit, class: 'food-field-input', placeholder: 'Measurement Unit. ex: Kg...' %>
  </div>

  <div class="food-field">
    <%= form.number_field :price, class: 'food-field-input', placeholder: 'Price $' %>
  </div>

  <div class="food-field">
    <%= form.number_field :quantity, class: 'food-field-input', placeholder: 'Quantity' %>
  </div>

  <div>
    <%= form.submit "Add new food", class: 'food-form-btn' %>
  </div>
<% end %>
</div>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<h1 class="new-food-header">Foods</h1>

<div class="foods">
    <%= button_to "New food", new_food_path, method: :get, class: 'foods-btn food-form-btn' %>
  <table class="food-table">
    <thead>
      <th class="food-t-name">Food</th>
      <th class="food-t-unit">Measurement Unit</th>
      <th class="food-t-price">Unit Price</th>
      <th class="food-t-actions">Actions</th>
    </thead>
    <% @foods.each do |food| %>
    <tbody>
      <tr>
        <td><%= link_to food.name, food_path(food) %></td>
        <td><%= food.measurement_unit %></td>
        <td><%= food.price %></td>
        <td><%= button_to "Delete", food, method: :delete, class: 'user-btn destroy-btn'  %></td>
      </tr>
    </tbody>
    <% end %>
  </table>
</div>

app/views/foods/new.html.erb
<h1 class="new-food-header">New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= button_to "Back to foods", foods_path, method: :get, class: 'user-btn food-btn' %>
</div>

app/views/foods/show.html.erb
<div id="<%= dom_id @food %>">
  <table>
    <tr style="display: flex; flex-direction: column">
      <td><%= @food.name %></td>
      <td><%= @food.price %></td>
      <td><%= @food.quantity %></td>
      <td><%= @food.measurement_unit %></td>
      <td><%= @food.created_at %></td>
      <td><%= @food.updated_at %></td>
      <td><%= @food.user_id %></td>
      <td><%= button_to "Delete", @food, method: :delete, class: 'user-btn destroy-btn'  %></td>
    </tr>
  </table>
</div>