config/routes.rb
Rails.application.routes.draw do
  resources :public_recipes, only: [:index]
  devise_for :users
  root to: "users#show"
  get 'general_shopping_list', to: 'shopping_list#index'
  resources :users
  resources :foods
  
  resources :recipes do
    resources :recipe_foods    
  end

  resources :recipes
  resources :recipe_foods
  resources :shopping_list

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_nav_bar.html.erb
<nav class="nav-bar">
  <ul class="nav-list">
    <li class="nav-item"><%= link_to '🔙', :back, class: 'normalize' %></li>
    <li class="nav-item"><%= link_to 'Foods', foods_path, class: 'normalize' %><li>
    <li class="nav-item"><%= link_to 'Recipes', recipes_path, class: 'normalize' %><li>
    <li class="nav-item"><%= link_to 'Public reciper', public_recipes_path, class: 'normalize' %><li>
    <li class="nav-item"><%= link_to 'General Shopping list', general_shopping_list_path, class: 'normalize' %> <li>
  </ul>
  <div class="page-title"><%= params[:controller] %></div>
  <ul class="nav-list">
    <li class="nav-item"><%= button_to "Sign out", destroy_user_session_path, method: :delete, class: 'user-btn' %></li>
    <li class="nav-item"><%= button_to "Delete my account", @user, method: :delete, class: 'user-btn destroy-btn' %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in?%>
      <%= render "layouts/nav_bar" %>
    <% end %>
    <% if notice %>
    <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>